[dev]
  command = "npm run develop"
  port = 8888 # You will visit http://localhost:8888
  targetPort = 8000 # Netlify will talk to Gatsby here
  publish = "public"
  autoLaunch = true

[[edge_functions]]
  path = "/how-to-live-a-good-life/*"
  function = "set-country"

[[edge_functions]]
  path = "/lifes-big-questions/*"
  function = "set-country"

[[edge_functions]]
  path = "/introduction-to-nietzsche/*"
  function = "set-country"